version: '3.8'
services:
  db:

    image: postgres:latest

    volumes:
      - /var/lib/postgresql/data/
      
    env_file:
      - /infra/.env

  web:
    image: trolraf/yamdb:latest

    restart: always
    
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/

    ports:
     - "8000:8000"

    depends_on:
      - db

    env_file:
      - /infra/.env 


  nginx:
    image: nginx:1.21.3-alpine


    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  postgres_data:
  static_value:
  media_value: